services:
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.106.1
    command: ["--config=/etc/cfg/otel/config.yaml"]
    volumes:
      - type: bind
        source: ./cfg/otel
        target: /etc/cfg/otel
        read_only: true
    ports:
      - "4317:4317"   # OTLP/gRPC
      - "4318:4318"   # OTLP/HTTP
      - "8888:8888"   # /metrics
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.56
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250"
      - "14268:14268"
