services:
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.106.1
    command: ["--config=/etc/cfg/otel/config.yaml"]
    volumes:
      - type: bind
        source: ./cfg/otel
        target: /etc/cfg/otel
        read_only: true
    ports:
      - "4317:4317"   # OTLP/gRPC
      - "4318:4318"   # OTLP/HTTP
      - "8888:8888"   # /metrics
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.56
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250"
      - "14268:14268"

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - type: bind
        source: ./cfg/prometheus
        target: /etc/prometheus
        read_only: true
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"   # Prometheus UI
    networks:
      - advcache_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana_data:/var/lib/grafana
      - type: bind
        source: ./cfg/grafana/provisioning
        target: /etc/grafana/provisioning
        read_only: true
      - type: bind
        source: ./cfg/grafana/dashboards
        target: /var/lib/grafana/dashboards
        read_only: true
    ports:
      - "3000:3000"   # Grafana UI
    depends_on:
      - prometheus
    networks:
      - advcache_network

volumes:
  prometheus_data:
  grafana_data:

networks:
  advcache_network:
    driver: bridge
